// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnfonzpwstsxetmznlsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZm9uenB3c3RzeGV0bXpubHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTI2OTUsImV4cCI6MjA2NzM4ODY5NX0.88ANEI_0jkeDdZ9PvcWHTdFEHzfb6GfPYeTH7_5QCcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});